<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<style>

*{-webkit-box-sizing: border-box;-moz-box-sizing: border-box;box-sizing: border-box;}

body,html{
	font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
	font-size: 15px;
	line-height: 1.5;
	margin: 0;
	padding: 0;
}

a{font-family: Verdana;color: #000;text-decoration: none;}
a:hover{color: 400;color: red}
.wraper{margin: 0 auto;max-width: 940px;}
.wraper h1{padding-top: 60px;padding-bottom: 60px;background-color: #eee;text-align: center;margin-top: -1px;color: #7f3fbf}
ul{padding-left: 20px;list-style-type: none;}
ul li{padding: 4px;border-bottom: 1px solid #eee;}
.wraper h1 span{display: block;font-size: 16px;color: #555;}

		</style>
	</head>
	<body>
	<div class="wraper">