<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<style>

*{-webkit-box-sizing: border-box;-moz-box-sizing: border-box;box-sizing: border-box;}

body,html{
	font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
	font-size: 15px;
	line-height: 1.5;
	margin: 0;
	padding: 0;
}

a{font-family: Verdana;color: #000;text-decoration: none;}
a:hover{color: 400;color: red}
.wraper{margin: 0 auto;max-width: 940px;border-top: 8px solid #ddd;}
.wraper h1{padding-top: 75px;padding-bottom: 75px;background-color: #eee;text-align: center;color: #7f3fbf;margin-top: -1px;}
ul{padding-left: 20px;list-style-type: none;overflow-x: hidden;}
ul li{padding: 8px;border-bottom: 1px solid #eee;}
ul li:hover{background-color: #f9f9f9;}
.wraper h1 span{background-color: #666;color: #fff;padding: 20px;font-size: 32px;}
.path{text-align: center;display: block;font-size: 15px;color:#888;background-color: #eee;padding: 8px 12px;}
		</style>
	</head>
	<body>
	<div class="wraper">
	<h1><span>File Listing</span></h1>